import Layout from "@/components/layout";


const ContactPage = () => {
    return (
        <Layout
        title={"Create Next App"}
        description={"Generated by create next app"}
      >
          <div>Contact page</div>
      </Layout>
    );
};

export default ContactPage;