import { useRef } from "react";

import Header from "@/components/header";
import Layout from "@/components/layout";
import BottomPageControl from "@/components/bottomPageControl";
import ContactContent from "@/components/contact/content";
import useMenu from "@/contexts/useMenu";
import useAnimateMenu from "@/hooks/animations/useAnimateMenu";
import { useBodyScroll, useBodyScrollLock } from "@/hooks/useBodyScroll";

import styles from "@/pages/contact/style.module.scss";


const ContactPage = () => {
  const menuBackground = useRef(null);

  const { isOpen } = useMenu();

  useAnimateMenu(isOpen, menuBackground);
  useBodyScroll(isOpen);
  useBodyScrollLock(isOpen);

  return (
    <>
      <div className={styles.header} ref={menuBackground}></div>
      <Layout
        title={"Create Next App"}
        description={"Generated by create next app"}
      >
        <div className={styles.container}>
          <Header
            title={"Contact"}
            description={"Contact me if you need to create project"}
          />
          <div className={styles.line}></div>
          <h1 className={styles.title}>Cyriac du Chatenet</h1>
          <ContactContent />
          <div className={styles.line}></div>
          <BottomPageControl link={"/projects"} label={"Projects"} />
        </div>
      </Layout>
    </>
  );
};

export default ContactPage;