services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    # volumes:
    #   - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
# volumes:
#   mongo_data:
#     driver: local