import { useState } from "react";

import Layout from "@/components/layout";
import useFetch from "@/hooks/useFetch";

import styles from '@/pages/projects/style.module.scss';


const ProjectsPage = () => {
  const [projectsData, setProjectsData] = useState([]);
  const [projectsDataError, setProjectsDataError] = useState([]);

  useFetch('/api/projects', 'GET', setProjectsData, setProjectsDataError);
  return (
    <Layout
    title={"Create Next App"}
    description={"Generated by create next app"}
  >
    <div className={styles.container}>Projects page</div>
  </Layout>
  );
};

export default ProjectsPage;
