import Layout from "@/components/layout";


const ProjectsPage = () => {
  return (
    <Layout
    title={"Create Next App"}
    description={"Generated by create next app"}
  >
    <div>Projects page</div>
  </Layout>
  );
};

export default ProjectsPage;
