import { useEffect, useRef, useState } from "react";
import gsap from "gsap";
import Link from "next/link";

import Layout from "@/components/layout";
import ContactFooter from "@/components/contactFooter";
import useFetch from "@/hooks/useFetch";

import styles from "@/pages/talks/style.module.scss";


const TalksPage = () => {
  const [talksData, setTalksData] = useState([]);
  const [talksDataError, setTalksDataError] = useState({});

  useFetch('/api/talks', 'GET', setTalksData, setTalksDataError);

  return (
    <Layout
      title={"Create Next App"}
      description={"Generated by create next app"}
    >
      <div className={styles.container}>
        <div className={styles.titleContainer}>
          <h1 className={styles.title}>Talks</h1>
          <p className={styles.description}>
            My different talks in developer conference
          </p>
        </div>
        <div className={styles.content}>
          <img
            src="https://secure.meetupstatic.com/photos/event/9/4/a/d/600_502718061.jpeg"
            alt=""
            className={styles.talkPreview}
          />
          <ul className={styles.talksList}>
            {talksData.map((talk) =>  <li key={talk._id} className={styles.talkCard}>
              <Link href={`/talk/${talk._id}`} className={styles.talkLink}>
                {talk.event_title} - {talk.title}
              </Link>
            </li>)}
          </ul>
        </div>
      </div>
      <ContactFooter />
    </Layout>
  );
};

export default TalksPage;
