import BottomPageControl from "@/components/bottomPageControl";
import Header from "@/components/header";
import Layout from "@/components/layout";
import TalksAboutSection from "@/components/talks/about";

import styles from "@/pages/talks/style.module.scss";

const TalksPage = () => {
  return (
    <>
      <header className={styles.header}></header>
      <Layout
        title={"Create Next App"}
        description={"Generated by create next app"}
      >
        <div className={styles.container}>
          <Header
            title={"Talks"}
            description={"My different talks in developer conference"}
          />
          <div className={styles.content}>
            <div className={styles.line}></div>
            <h2 className={styles.title}>Tech Ctrl</h2>
            <div className={styles.videoContainer}>
              <video controls className={styles.videoPlayer}>
                <source
                  src="https://www.youtube.com/watch?v=r_JTTswNdIs"
                  type="video/mp4"
                />
              </video>
            </div>
            <TalksAboutSection />
            <div className={styles.line}></div>
            <BottomPageControl link={"/contact"} label={"Contact"} />
          </div>
        </div>
      </Layout>
    </>
  );
};

export default TalksPage;
