import Layout from "@/components/layout";
import Header from "@/components/header";
import BottomPageControl from "@/components/bottomPageControl";
import Skills from "@/components/about/skills";

import styles from "@/pages/about/style.module.scss";
import AboutSection from "@/components/about";


const AboutPage = () => {
  return (
    <>
      <header className={styles.header}></header>
      <Layout
        title={"Create Next App"}
        description={"Generated by create next app"}
      >
        <div className={styles.container}>
          <Header title={'About me'} description={'I’m self-taugh creative developer and Ux - Ui designer'} />
            <AboutSection />
            <Skills />
            <div className={styles.line}></div>
            <BottomPageControl link={'/contact'} label={'Contact'} />
        </div>
      </Layout>
    </>
  );
};

export default AboutPage;