import Layout from "@/components/layout";


const AboutPage = () => {
    return (
        <Layout
        title={"Create Next App"}
        description={"Generated by create next app"}
      >
                <div>About page</div>
      </Layout>
    );
};

export default AboutPage;