import { useEffect, useRef } from "react";

import Layout from "@/components/layout";
import Header from "@/components/header";
import BottomPageControl from "@/components/bottomPageControl";
import Skills from "@/components/about/skills";
import AboutSection from "@/components/about";
import useMenu from "@/contexts/useMenu";
import useAnimateMenu from "@/hooks/animations/useAnimateMenu";
import { useBodyScroll, useBodyScrollLock } from "@/hooks/useBodyScroll";

import styles from "@/pages/about/style.module.scss";


const AboutPage = () => {
  const menuBackground = useRef(null);

  const { isOpen } = useMenu();

  useAnimateMenu(isOpen, menuBackground);
  useBodyScroll(isOpen);
  useBodyScrollLock(isOpen);

  return (
    <>
      <header className={styles.header} ref={menuBackground}></header>
      <Layout
        title={"Create Next App"}
        description={"Generated by create next app"}
      >
        <div className={styles.container}>
          <Header title={'About me'} description={'I’m self-taugh creative developer and Ux - Ui designer'} />
            <AboutSection />
            <Skills />
            <div className={styles.line}></div>
            <BottomPageControl link={'/contact'} label={'Contact'} />
        </div>
      </Layout>
    </>
  );
};

export default AboutPage;