import { useEffect, useRef } from "react";

import BaselineFooter from "@/components/baselineFooter";
import Layout from "@/components/layout";
import Loader from "@/components/loader";
import Cubes from "@/components/home/cubes";
import { useLoader } from "@/contexts/useLoader";
import useMenu from "@/contexts/useMenu";
import { useBodyScroll, useBodyScrollLock } from "@/hooks/useBodyScroll";

import styles from "@/styles/Home.module.scss";

const HomePage = () => {
  const creativeTitle = useRef(null);
  const developerTitle = useRef(null);
  const description = useRef(null);

  const { isOpen } = useMenu();
  const { isLoading } = useLoader();

  useBodyScroll(isOpen);
  useBodyScrollLock(isOpen);

  useEffect(() => {
    document.body.style.overflow = 'hidden';
  }, []);

  return (
    <>
      {isLoading === false ? <Loader /> : null}
      <div className={styles.container}>
        <Layout
          title={"Create Next App"}
          description={"Generated by create next app"}
        >
          <Cubes />
          <main className={styles.main}>
            <div className={styles.content}>
              <div className={styles.titleContainer}>
                <p className={styles.title} ref={creativeTitle}>
                  Creative
                </p>
                <p className={styles.devTitle} ref={developerTitle}>
                  Developer
                </p>
              </div>
              <p className={styles.description} ref={description}>
                Ux - Ui designer X developer fullstack
              </p>
            </div>
            <BaselineFooter displayTalks={true} />
          </main>
        </Layout>
      </div>
    </>
  );
};

export default HomePage;
