import Layout from "@/components/layout";
import useMenu from "@/contexts/useMenu";
import { useBodyScroll, useBodyScrollLock } from "@/hooks/useBodyScroll";


const ProjectPage = () => {
    const { isOpen } = useMenu();

    useBodyScroll(isOpen);
    useBodyScrollLock(isOpen);

    return (
        <Layout
        title={"Create Next App"}
        description={"Generated by create next app"}
      >  
          <div>Project page</div>
      </Layout>
    );
};

export default ProjectPage;