import Layout from "@/components/layout";


const ProjectPage = () => {
    return (
        <Layout
        title={"Create Next App"}
        description={"Generated by create next app"}
      >  
          <div>Project page</div>
      </Layout>
    );
};

export default ProjectPage;